on: push
name: Test Update
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set remote url
        run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: package-update
        uses: ghustavh97/actions-package-update@test
        env:
          AUTHOR_EMAIL: ryushi@gmail.com
          AUTHOR_NAME: taichi
          EXECUTE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
          SET_NODE_VERSION: 14
        with:
          args: -u --packageFile package.json --loglevel verbose
